title: Miriam Tocino
email: miriam.tocino@gmail.com
description: "Teaching & Coding"

author :
  name : Miriam Tocino
  email : miriam.tocino@gmail.com
  github : miriamtocino
  twitter : miriamtocino
  feedburner : feedname

url: "http://www.miriamtocino.com"

twitter_username:   miriamtocino
github_username:    miriamtocino
pinterest_username: miriamtocino
bitbucket_username: miriamtocino
linkedin_username:  miriamtocino
instagram_username: miriamtocino

permalink: /articles/:title
paginate: 30

navigation:
  # - title: Resources
  #   url: /resources.html
  - title: Elearning
    url: /elearning.html
  - title: Bookshelf
    url: /bookshelf.html
  # - title: Projects
  #   url: /projects.html
  - title: Archive
    url: /archive.html

gems: [jekyll-paginate]
